---
name: Test foreman_plugin.yml

on:
  pull_request:
    paths:
      - '.github/workflows/foreman_plugin.yml'
      - '.github/workflows/foreman_plugin_workflow_test.yml'

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    name: Ruby
    strategy:
      fail-fast: false
      matrix:
        plugin:
          - foreman-tasks
          - foreman_remote_execution
    uses: ./.github/workflows/foreman_plugin.yml
    with:
      plugin: ${{ matrix.plugin }}
      plugin_repository: theforeman/${{ matrix.plugin }}
