---
name: Release gem

on:
  workflow_call:
    inputs:
      allowed_owner:
        description: 'Only allow this owner. Used to prevent releasing on forks'
        required: true
        type: 'string'
      ruby_version:
        description: 'Ruby version used to build'
        default: 'ruby'
        type: 'string'
    secrets:
      rubygems_oidc_role:
        description: 'The OIDC role to assume'
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository_owner == inputs.allowed_owner
    steps:
      - uses: actions/checkout@v4
      - name: 'Install Ruby ${{ inputs.ruby_version }}'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '${{ inputs.ruby_version }}'
      - name: Build gem
        run: gem build *.gemspec
      - uses: rubygems/configure-rubygems-credentials@v1.0.0
        with:
          role-to-assume: ${{ secrets.rubygems_oidc_role }}
      - name: Publish gem to rubygems.org
        run: gem push *.gem
      - name: Wait for release to propagate
        run: |
          gem install rubygems-await
          gem await *.gem
